import Head from "next/head";
import { RxHamburgerMenu, RxCrossCircled } from "react-icons/rx";
import * as NavigationMenu from "@radix-ui/react-navigation-menu";
import * as Dialog from "@radix-ui/react-dialog";
import styles from "../styles/Home.module.css";
import { Fragment } from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="no-flow-x-center fixed flex w-full items-center justify-between bg-white py-2 px-4 drop-shadow-lg md:container md:mx-auto md:mt-2">
        {/* Information */}
        <div className="flex items-center gap-3">
          <img className="h-[min(2.5rem,_10vw)]" src="/logo-lolla.png" alt="Lollapalooza 10ª Edição Brasil" />
          <div className="text-xs font-semibold sm:text-sm">
            <p>24, 25 e 26 de março de 2023</p>
            <p className="hidden sm:block">São Paulo</p>
          </div>
        </div>
        {/* Mobile Navigation Menu */}
        <Dialog.Root>
          <Dialog.Trigger className="flex lg:hidden">
            <RxHamburgerMenu size="1.5rem" />
          </Dialog.Trigger>
          <Dialog.Portal>
            <Dialog.Overlay className="fixed inset-0 bg-black bg-opacity-10 backdrop-blur-md" />
            <Dialog.Content className="fixed top-0 bottom-0 right-0 bg-white px-4 py-2">
              <Dialog.Title className="DialogTitle">Navigation Menu</Dialog.Title>
              <ul>
                <li>
                  <Dialog.Close>
                    <a href="#">Merchan</a>
                  </Dialog.Close>
                </li>
                <li>
                  <Dialog.Close>
                    <a href="#">Lockers</a>
                  </Dialog.Close>
                </li>
                <li>
                  <Dialog.Close>
                    <a href="#">Pacotes de Viagem</a>
                  </Dialog.Close>
                </li>
                <li>
                  <Dialog.Close>
                    <a href="#">Transfer</a>
                  </Dialog.Close>
                </li>
                <li>
                  <Dialog.Close>
                    <a href="#">Slideshows</a>
                  </Dialog.Close>
                </li>
              </ul>
              <Dialog.Close>
                <button className="absolute top-2 right-2" aria-label="Close">
                  <RxCrossCircled />
                </button>
              </Dialog.Close>
            </Dialog.Content>
          </Dialog.Portal>
        </Dialog.Root>
        {/* Desktop Navigation Menu */}
        <NavigationMenu.Root className="hidden lg:inline">
          <NavigationMenu.List className="flex space-x-4">
            <NavigationMenu.Item>
              <NavigationMenu.Trigger>Produtos</NavigationMenu.Trigger>
              <NavigationMenu.Content className="absolute">
                <ul>
                  <li>
                    <NavigationMenu.Link href="#">Merchan</NavigationMenu.Link>
                  </li>
                  <li>
                    <NavigationMenu.Link href="#">Lockers</NavigationMenu.Link>
                  </li>
                  <li>
                    <NavigationMenu.Link href="#">Pacotes de Viagem</NavigationMenu.Link>
                  </li>
                  <li>
                    <NavigationMenu.Link href="#">Transfer</NavigationMenu.Link>
                  </li>
                  <li>
                    <NavigationMenu.Link href="#">Slideshows</NavigationMenu.Link>
                  </li>
                </ul>
              </NavigationMenu.Content>
            </NavigationMenu.Item>

            <NavigationMenu.Item>
              <NavigationMenu.Trigger>Informações</NavigationMenu.Trigger>
              <NavigationMenu.Content className="absolute">
                <ul>
                  <li>
                    <NavigationMenu.Link href="https://github.com/radix-ui">FAQ</NavigationMenu.Link>
                  </li>
                  <li>
                    <NavigationMenu.Link href="https://github.com/radix-ui">Entrada Social</NavigationMenu.Link>
                  </li>
                </ul>
              </NavigationMenu.Content>
            </NavigationMenu.Item>

            <NavigationMenu.Item>
              <NavigationMenu.Trigger>Experiência</NavigationMenu.Trigger>
              <NavigationMenu.Content className="absolute">
                <ul>
                  <li>
                    <NavigationMenu.Link href="https://github.com/radix-ui">O Festival</NavigationMenu.Link>
                  </li>
                </ul>
              </NavigationMenu.Content>{" "}
            </NavigationMenu.Item>

            <NavigationMenu.Item>
              <NavigationMenu.Link href="https://github.com/radix-ui">Contato</NavigationMenu.Link>
            </NavigationMenu.Item>

            <NavigationMenu.Item>
              <NavigationMenu.Link href="https://github.com/radix-ui">Ingressos</NavigationMenu.Link>
            </NavigationMenu.Item>
          </NavigationMenu.List>
        </NavigationMenu.Root>
      </header>

      <main>
        {/* Lineup Section */}
        <section className="bg-[url('/background-blue-sun.jpg')] bg-fixed bg-center pt-[15vh]">
          {/* Announcement & Lineup */}
          <div className="container mx-auto mb-8 xl:px-[10vw]">
            <img src="header-content-1080p.png" className="mx-auto mb-[clamp(2rem,8vw,4rem)]" />
            <div className="mx-auto grid grid-cols-7 content-center px-4 pb-4">
              <img src="lineup-style-left.png" className="hidden sm:block" />
              <img src="lineup-content.png" className="col-span-full justify-self-center sm:col-span-5" />
              <img src="lineup-style-right.png" className="hidden sm:block" />
            </div>
          </div>
          {/* City BG */}
          <div className="bottom-0 left-0 right-0 h-36 bg-[url('/background-row-city.png')] bg-top bg-repeat-x" />
        </section>
        {/* Our Products Section */}
        {/* Check Everything that Happened */}
        {/* Lolla is Global */}
        {/* Footer */}
      </main>
    </>
  );
}
